import './globals.css'
import { Inter } from 'next/font/google'
import Header from "../header"
import Footer from '../footer'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { UserProvider } from '../userContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Header/>
            {children}
          <Footer/>
        </UserProvider>
      </body>
    </html>
  )
}
