'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from "../header"
import Footer from '../footer'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { UserProvider } from '../userContext'
const inter = Inter({ subsets: ['latin'] })
import { usePathname } from 'next/navigation';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const hideHeaderFooter = pathname === '/auth' || pathname === '/auth/register';
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          {!hideHeaderFooter && <Header />}
            {children}
          {!hideHeaderFooter && <Footer />}
        </UserProvider>
      </body>
    </html>
  )
}
